aliases = [ "es2021" ]
dependencies = [
	"_ESAbstract.CreateDataPropertyOrThrow",
	"_ESAbstract.GetIterator",
	"Array.from",
	"Array.isArray",
	"Object.setPrototypeOf",
]
license = "MIT"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError"

[browsers]
android = "<85"
bb = "*"
chrome = "<85"
firefox = "<79"
ios_saf = "<14"
edge = "<85"
edge_mob = "<85"
ie = "*"
ie_mob = "*"
opera = "*"
op_mini = "*"
safari = "<14"
firefox_mob = "<79"
samsung_mob = "<14"
