aliases = [ "es2020" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.GetIterator",
	"_ESAbstract.Type",
	"Array.from",
	"Array.isArray",
	"Array.prototype.map",
	"Promise",
]
license = "MIT"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled"

[browsers]
android = "<76"
bb = "*"
chrome = "<76"
firefox = "<71"
ios_saf = "<13"
edge = "<79"
edge_mob = "<79"
ie = "*"
ie_mob = "*"
opera = "<63"
op_mini = "*"
safari = "<13"
firefox_mob = "<79"
samsung_mob = "<12"
